<<<<<<< HEAD
<!-- Generated by ::xowiki::ADP_Generator on Mon Feb 25 08:41:48 PST 2019 -->
=======
<!-- Generated by ::xowiki::ADP_Generator on Sun Feb 24 21:31:54 PST 2019 -->
>>>>>>> 528929904d7e2ccb082474d1a1d5c38a081b0d3f
<!-- The following DIV is needed for overlib to function! -->
          <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>    
          <div class='xowiki-content'>

@top_includelets;noquote@
 <if @page_context@ not nil><h1>@title@ (@page_context@)</h1></if>
 <else><h1>@title@</h1></else>
 <if @folderhtml@ not nil> 
 <div class='folders' style=''>@folderhtml;noquote@</div> 
 <div class='content-with-folders'>@content;noquote@</div> 
 </if>
    <else>@content;noquote@</else>

</div> <!-- class='xowiki-content' -->
